---
title: "Resources"
---

### Introductions to Bayesian inference

- Rasmus Bååth has created a three-part video-lecture introducing Bayesian data analysis [Part 1](https://youtu.be/3OJEae7Qb_o?si=Us9J3IoETr1Kp9ll), [Part 2](https://youtu.be/mAUwjSo5TJE?si=la5tYC3Vjf_SSdJo) and [Part 3](https://youtu.be/Ie-6H_r7I5A?si=FHbeCfkCisD1Ims6).

- [A visual introduction to Bayesian inference](https://seeing-theory.brown.edu/bayesian-inference/index.html)


### Resources for fitting and learning Bayesian data modelling

- [Statistical rethinking with brms, ggplot2, and the tidyverse: Second edition](https://bookdown.org/content/4857/) by Solomon Kurz is a thorough parallel reading of *Statistical Rethinking* with all models implemented in the [`brms`](https://github.com/paul-buerkner/brms) package.

- [The brms Book: Applied Bayesian Regression Modelling Using R and Stan (Early Draft)](https://paulbuerkner.com/software/brms-book/) by Paul Bürkner. This book introduces the [`brms`](https://github.com/paul-buerkner/brms) package along with Bayesian regression modelling.

- [The stan user guide](https://mc-stan.org/docs/stan-users-guide/) by the Stan Development Team provides examples on programming models in the Stan language.
