project:
  type: book

book:
  title: "Statistical Rethinking Seminars"
  author: "Daniel Hammarström"
  date: "2024-12-14"
  chapters:
    - index.qmd
    - 00-resources.qmd
    - 01-notation.qmd
    - 05-ch4-stanmodels.qmd
    
brand: _brand.yml
bibliography: resources/references.bib
css: style.css

format:
  html: 
    code-tools:
      source: true
      toggle: false
      caption: none
code-block-bg: true
code-block-border-left: "#31BAE9"
highlight-style: atom-one