# Preface


These pages include notes and resources for the *Statistical Rethinking Seminars* at the Faculty of Social and Health Sciences, at the University of Inland Norway. The seminar series is organized as a [course accredited as part of the PhD program Health and Welfare](https://www.inn.no/english/study-options/our-studies/statistical-rethinking/).


## What and How we learn
This series of seminars is based on the book [*Statistical Rethinking*](https://www.routledge.com/Statistical-Rethinking-A-Bayesian-Course-with-Examples-in-R-and-STAN/McElreath/p/book/9780367139919) by Richard McElreath. The book introduces Bayesian statistics and probabilistic programming in the context of scientific research. The book helps you to develop a principled approach to statistical analysis. 

We will meet every week for discussions. Meetings will be held as seminars to discuss the book's material and exercises. This learning strategy requires you to prepare to participate actively in discussions. Preparation includes reading the relevant chapters, watching the lectures, and working on the exercises. Many exercises require coding in your preferred coding environment. The book mostly includes R code, but other programming languages have also been used to work on the material (see resources).

The seminar series follows the same structure as the [course given by Richard McElreath (in 2025)](https://github.com/rmcelreath/stat_rethinking_2025) @tbl-content. Beginning on the 22nd of January 2026, we will meet weekly for 10 weeks.


## Prerequisites and resources

There are no formal prerequisites for the seminar series. However, knowing basic R programming will make your experience easier when reading the book, watching the lectures, and completing the exercises. Experience with statistical analysis will also be helpful. The final assignment in the course will require you to perform a data analysis on data of your choosing. It is expected that the analysis is performed using reproducible programming. The R programming language and auxiliary tools are discussed [here](https://dhammarstrom.github.io/r-crash-course/), along with instructions for setting up software for reproducible programming. 

You can find resources related to Bayesian modelling [here](00-resources.qmd)


|Week |Date (time) |Chapters |Lectures|
|---|---|---|---|
|4  |2026-01-22 (13:00)|1-3  |[1, 2](https://www.youtube.com/playlist?list=PLDcUM9US4XdPz-KxHM4XHt7uUVGWWVSus)
|5  |2026-01-29 (13:00)|4    |[3, 4](https://www.youtube.com/playlist?list=PLDcUM9US4XdPz-KxHM4XHt7uUVGWWVSus) 
|6  |2026-02-05 (13:00)|5-6  |[5, 6](https://www.youtube.com/playlist?list=PLDcUM9US4XdPz-KxHM4XHt7uUVGWWVSus)
|7  |2026-02-12 (13:00)|7-9  |[7, 8](https://www.youtube.com/playlist?list=PLDcUM9US4XdPz-KxHM4XHt7uUVGWWVSus)
|8  |2026-02-19 (13:00)|10-11|[9, 10](https://www.youtube.com/playlist?list=PLDcUM9US4XdPz-KxHM4XHt7uUVGWWVSus)
|9  |2026-02-26 (13:00)|11-12|[11, 12](https://www.youtube.com/playlist?list=PLDcUM9US4XdPz-KxHM4XHt7uUVGWWVSus)
|10 |2026-03-05 (13:00)|13   |[13, 14](https://www.youtube.com/playlist?list=PLDcUM9US4XdPz-KxHM4XHt7uUVGWWVSus)
|11 |2026-03-12 (13:00)|14   |[15, 16](https://www.youtube.com/playlist?list=PLDcUM9US4XdPz-KxHM4XHt7uUVGWWVSus)
|12 |2026-03-19 (13:00)|15   |[17, 18](https://www.youtube.com/playlist?list=PLDcUM9US4XdPz-KxHM4XHt7uUVGWWVSus)
|13 |2026-03-26 (13:00)|16-17|[19, 20](https://www.youtube.com/playlist?list=PLDcUM9US4XdPz-KxHM4XHt7uUVGWWVSus)

: The course schedule {#tbl-content}









